influxdb:
  image: tutum/influxdb:0.13
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"

grafana:
  image: grafana/grafana:4.1.1
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
